inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Security/Eval:
  Exclude:
    - app/models/question.rb

Lint/UselessAssignment:
  Exclude:
    - app/models/question.rb
